const images = [
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g12.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g13.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g14.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g15.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g18.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g19.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g20.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g21.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g22.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g23.jpeg",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g1.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g2.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g3.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g4.png",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g5.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g6.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g7.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g8.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g9.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g10.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g11.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n7.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n8.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n9.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n4.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n5.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n6.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n10.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n11.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n12.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n13.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n5.png",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n4.png",
  },

  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n3.png",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n1.png",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n2.png",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new7.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new8.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new9.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new10.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new11.jpeg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new12.jpeg",
  },
  {
    type: "",
    title: "Final: SS vs NMP",
    date: "27 May, 2025",
    img: "/images/gallery/new1.jpg",
    views: 1289,
  },
  {
    type: "",
    title: "T20 Mumbai Promo",
    date: "",
    img: "/images/gallery/new-2.jpg",
    views: 1500,
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/new3.jpg",
  },
  {
    type: "",
    title: "Final: SS vs NMP",
    date: "27 May, 2025",
    img: "/images/gallery/new-1.jpeg",
    views: 1289,
  },
  {
    type: "",
    title: "T20 Mumbai Promo",
    date: "",
    img: "/images/gallery/new5.jpg",
    views: 1500,
  },
  {
    type: "",
    title: "Final: SS vs NMP",
    date: "27 May, 2025",
    img: "/images/gallery/img3.jpg",
    views: 1289,
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/new6.jpg",
  },

  //newly updated galary

  {
    type: "",
    title: "T20 Mumbai Promo",
    date: "",
    img: "/images/gallery/img2.jpg",
    views: 1500,
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/img11.jpg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/img4.jpg",
  },
  {
    type: "",
    title: "T20 Mumbai Promo",
    date: "",
    img: "/images/gallery/img12.jpg",
    views: 1500,
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/img10.jpg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/img7.jpg",
  },
  {
    type: "",
    title: "Final: SS vs NMP",
    date: "27 May, 2025",
    img: "/images/gallery/img8.jpg",
    views: 1289,
  },
  {
    type: "",
    title: "T20 Mumbai Promo",
    date: "",
    img: "/images/gallery/img9.png",
    views: 1500,
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/img10.jpg",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/img11.jpg",
  },
];

const ImageFolders = {
  "Match 1": [
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g1.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g2.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g3.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g4.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g5.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g6.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g7.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g8.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g9.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/g10.jpeg",
    },
  ],
  "Match 2": [
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n7.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n8.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n9.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n4.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n5.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n6.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n10.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n11.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n12.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n13.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n5.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n4.png",
    },

    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n3.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n1.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n2.png",
    },
  ],
  "Match 3": [
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n7.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n8.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n9.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n4.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n5.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n6.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n10.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n11.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n12.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n13.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n5.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n4.png",
    },

    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n3.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n1.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n2.png",
    },
  ],

  "Match 4": [
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n7.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n8.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n9.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n4.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n5.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n6.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n10.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n11.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n12.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n13.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n5.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n4.png",
    },

    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n3.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n1.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n2.png",
    },
  ],

  "Match 5": [
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n7.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n8.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n9.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n4.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n5.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n6.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n10.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n11.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n12.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n13.jpeg",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n5.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n4.png",
    },

    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n3.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n1.png",
    },
    {
      type: "",
      title: "Dreams do come true",
      date: "27 May, 2025",
      img: "/images/gallery/n2.png",
    },
  ],
};

export {images, ImageFolders};
