const images = [ 
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g1.jpeg",
    size:"small",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g2.jpeg",
    size:"small",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g3.jpeg",
    size:"medium",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g4.png",
    size:"medium",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g5.jpeg",
    size:"large",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g6.jpeg",
    size:"medium",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g7.jpeg",
    size:"small",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g8.jpeg",
    size:"medium",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g9.jpeg",
    size:"medium",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g10.jpeg",
    size:"large",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/g11.jpeg",
    size:"medium",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n7.jpeg",
    size:"medium",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n8.jpeg",
    size:"medium",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n9.jpeg",
    size:"small",
  },
   {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n4.jpeg",
    size:"medium",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n5.jpeg",
    size:"small",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n6.jpeg",
    size:"small",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n10.jpeg",
    size:"medium",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n11.jpeg",
    size:"small",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n12.jpeg",
    size:"small",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n13.jpeg",
    size:"large",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n5.png",
    size:"small",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n4.png",
    size:"medium",
  },

  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n3.png",
    size:"large",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n1.png",
    size:"small",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/n2.png",
    size:"large",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new7.jpeg",
    size:"medium",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new8.jpeg",
    size:"medium",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new9.jpeg",
    size:"medium",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new10.jpeg",
    size:"small",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new11.jpeg",
    size:"small",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/new12.jpeg",
    size:"small",
  },
  {
    type: "",
    title: "Final: SS vs NMP",
   date: "27 May, 2025",
    img: "/images/gallery/new1.jpg",
    views: 1289,
    size:"medium",
  },
  {
    type: "",
    title: "T20 Mumbai Promo",
   date: "",
    img: "/images/gallery/new-2.jpg",
    views: 1500,
    size:"medium",
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/new3.jpg",
    size:"large",
  },
  {
    type: "",
    title: "Final: SS vs NMP",
   date: "27 May, 2025",
    img: "/images/gallery/new-1.jpeg",
    views: 1289,
    size:"small",
  },
  {
    type: "",
    title: "T20 Mumbai Promo",
   date: "",
    img: "/images/gallery/new5.jpg",
    views: 1500,
    size:"large",
  },
  {
    type: "",
    title: "Final: SS vs NMP",
   date: "27 May, 2025",
    img: "/images/gallery/img3.jpg",
    views: 1289,
    size:"large"
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/new6.jpg",
    size:"small",
  },

  //newly updated galary

  {
    type: "",
    title: "T20 Mumbai Promo",
   date: "",
    img: "/images/gallery/img2.jpg",
    views: 1500,
    size:"medium",
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/img11.jpg",
    size:"large",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/img4.jpg",
    size:"small",
  },
  {
    type: "",
    title: "T20 Mumbai Promo",
   date: "",
    img: "/images/gallery/img12.jpg",
    views: 1500,
    size:"large",
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/img10.jpg",
    size:"large",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/img7.jpg",
    size:"large"
  },
  {
    type: "",
    title: "Final: SS vs NMP",
   date: "27 May, 2025",
    img: "/images/gallery/img8.jpg",
    views: 1289,
    size:"small",
  },
  {
    type: "",
    title: "T20 Mumbai Promo",
   date: "",
    img: "/images/gallery/img9.png",
    views: 1500,
    size:"large",
  },
  {
    type: "",
    title: "Match 19: NBB vs ET",
    date: "22 May, 2025",
    img: "/images/gallery/img10.jpg",
    size:"large",
  },
  {
    type: "",
    title: "Dreams do come true",
    date: "27 May, 2025",
    img: "/images/gallery/img11.jpg",
    size:"medium",
  },
  
];


export default images;